services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: notificate_api
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq/
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: notificate_bot
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq/
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    depends_on:
      rabbitmq:
        condition: service_healthy 